### ISSUE TITLE
Timer läuft weiter auch wenn Host leer ist.

### ISSUE THREAD

**Issue by Nall-chan** [Schnittcher/IPS-PiHole#1]
Da fehlt der Else Zweig im ApplyChanges.
So läuft der Timer weiter auch wenn Host inzwischen leer ist.

**Comment by Schnittcher** [comment]
Natürlich... :D

Michael Tröger <notifications@github.com> schrieb am Mi. 15. Aug. 2018 um
00:05:

**Comment by Schnittcher** [comment]
Gefixt
