### ISSUE TITLE
keine Fehlerbehandlung wenn pihole nicht erreichbar

### ISSUE THREAD

**Issue by Nall-chan** [Schnittcher/IPS-PiHole#2]
https://github.com/Schnittcher/IPS-PiHole/blob/0af2f318d432e1b410fb7fdae7ba9fe61788e13f/IPS-PiHole/module.php#L49
Sollte eine Fehlermeldung z.b. mit Echo ausgeben.

**Comment by Schnittcher** [comment]
Gefixt.
