### ISSUE TITLE
Request hat keinen Rückgabewert im Fehlerfall

### ISSUE THREAD

**Issue by Nall-chan** [Schnittcher/IPS-PiHole#3]
https://github.com/Schnittcher/IPS-PiHole/blob/0af2f318d432e1b410fb7fdae7ba9fe61788e13f/IPS-PiHole/module.php#L42

Alle Methoden welche request nutzen, prüfen nicht ob der Rückgabewert ungleich Null ist.
Folgefehler wenn z.b. der pihole offline ist oder der Host falsch/leer ist und die InstanzFunktionen aufgerufen werden bzw. RequestAction genutzt wird.

**Comment by Schnittcher** [comment]
Baue ich morgen ein!
Brauche ich ja nur auf ungleich NULL prüfen und wenn es zutrifft weiter machen, sonst nichts mehr, da die Meldung ja schon vorher ausgegeben wird.

**Comment by Schnittcher** [comment]
Gefixt.
