### ISSUE TITLE
redundanten Code

### ISSUE THREAD

**Issue by Nall-chan** [Schnittcher/IPS-PiHole#4]
https://github.com/Schnittcher/IPS-PiHole/blob/bdee7e2fa23794b24b2553243d2d22c8f6bd488b/IPS-PiHole/module.php#L99
Kann entfallen und durch 
$this->setStatus($Value);
Ersetzt werden.

**Comment by Nall-chan** [comment]
https://github.com/Schnittcher/IPS-PiHole/blob/bdee7e2fa23794b24b2553243d2d22c8f6bd488b/IPS-PiHole/module.php#L71
Kann ebenfalls alles entfallen und durch einen Einzeiler ersetzt werden
$data = $this->request(($value ? "enable" : "disable"));

**Comment by Schnittcher** [comment]
Zum zweiten, das finde ich persönlich immer so unleserlich.
Macht das in großen Projekten von der Performance her einen großen Unterschied?

**Comment by Schnittcher** [comment]
Gefixt. Kannst mir die Frage ja auch per PN im Forum beantworten.
